name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'studenthub-frontend/package-lock.json'

      - name: Install and Build 🔧
        run: |
          cd studenthub-frontend
          npm ci
          npm run build

      - name: Copy index.html to 404.html 4️⃣0️⃣4️⃣
        run: |
          cp studenthub-frontend/dist/index.html studenthub-frontend/dist/404.html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: studenthub-frontend/dist
          branch: gh-pages
